// Story 2.31 — frontend ESLint flat config.
// Re-authored from scratch (story 2.1 deleted the Vite-template config).
// `eslint-config-prettier` is applied LAST to disable stylistic rules Prettier owns (AC2).
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import importPlugin from 'eslint-plugin-import';
import prettier from 'eslint-config-prettier';
import localRules from './tools/eslint-rules/index.js';

export default tseslint.config(
  // Never lint build output, deps, or the module-local Node install.
  // `src/routeTree.gen.ts` (story 2.5) is machine-generated by the TanStack Router
  // Vite plugin — linting it is noise and would fail the strict ruleset.
  {
    ignores: [
      'dist/**',
      'target/**',
      'node_modules/**',
      '.frontend-node/**',
      'coverage/**',
      'src/routeTree.gen.ts',
      // Story 2.27 — Playwright run output (reports + traces), never linted.
      'playwright-report/**',
      'test-results/**',
    ],
  },

  js.configs.recommended,

  // ---- Application source: type-aware TS + React + a11y (AC1, AC3, AC6) ----
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [
      ...tseslint.configs.recommendedTypeChecked,
      react.configs.flat.recommended,
      react.configs.flat['jsx-runtime'],
      jsxA11y.flatConfigs.recommended,
    ],
    languageOptions: {
      parserOptions: {
        // Type-aware linting without enumerating tsconfig paths; honours the
        // strict flags in tsconfig.app.json (story 2.1).
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.browser },
    },
    settings: {
      react: { version: 'detect' },
      // eslint-plugin-import resolves TS + the `@/*` alias (added by story 2.2).
      'import/resolver': { typescript: true },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      import: importPlugin,
      'local-rules': localRules,
    },
    rules: {
      // AC3 — TypeScript strict rules
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/strict-boolean-expressions': 'warn',
      '@typescript-eslint/no-unnecessary-condition': 'warn',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-misused-promises': 'error',

      // react-hooks (v5 — set explicitly for flat-config portability)
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // import hygiene — TypeScript already enforces module resolution, so
      // no-unresolved is delegated to tsc to avoid false positives on the
      // `@/*` alias before story 2.2 wires it.
      'import/no-unresolved': 'off',
      'import/no-duplicates': 'error',

      // AC6 — jsx-a11y rules at error (supports WCAG 2.1 AA, story 2.25)
      'jsx-a11y/anchor-is-valid': 'error',
      'jsx-a11y/click-events-have-key-events': 'error',
      'jsx-a11y/no-autofocus': 'error',
      'jsx-a11y/role-has-required-aria-props': 'error',
      'jsx-a11y/aria-props': 'error',
      'jsx-a11y/aria-proptypes': 'error',
      'jsx-a11y/aria-unsupported-elements': 'error',
      'jsx-a11y/interactive-supports-focus': 'error',
      'jsx-a11y/no-noninteractive-element-interactions': 'error',
      'jsx-a11y/label-has-associated-control': 'error',

      // AC5 — query keys must come from a factory (forward-looking to 2.6)
      'local-rules/no-inline-query-keys': 'error',

      // Story 2.24 AC11 — no `dangerouslySetInnerHTML` / `innerHTML` writes
      // outside the sanitization package's trusted boundary.
      'local-rules/no-unsanitized-html': 'error',

      // Story 2.22 AC7 — <LoadingState> needs an explicit variant; no raw
      // spinners outside src/components/feedback/states + src/components/ui.
      'local-rules/no-untyped-loading-state': 'error',

      // Story 2.21 AC2 — a workflow-significant outcome must never be signalled
      // by toast alone (UX-DR15): in a file importing a workflow-mutation hook,
      // toast.success/error/warning (sonner or feedbackToast) is forbidden;
      // toast.info/feedbackToast.info (ancillary) stays allowed.
      'local-rules/no-workflow-toast-success': 'error',

      // Story 2.23 AC7 — at most one literal priority="primary" within a single
      // <ButtonGroup>/<DecisionArea> (UX-DR19 one primary per decision area).
      'local-rules/single-primary-action': 'error',

      // Story 2.23 AC3 — a <ConfirmationDialog> whose confirm handler ONLY
      // navigates / enters compare is forbidden (UX-DR18 no modal confirmation
      // for low-risk navigation; confirmationCatalog.ts is authoritative).
      'local-rules/no-confirmation-for-navigation': 'error',

      // Story 2.25 AC8 — actor-role text must render via <AuditRoleLabel> (a
      // recorded audit label, not enforced authorization), never bare.
      'local-rules/no-bare-actor-role-text': 'error',

      // Story 2.25 AC9 (hard invariant) — never gate actions on an audit role;
      // all gating routes through useAllowedActions (story 2.14).
      'local-rules/no-role-based-action-gating': 'error',
    },
  },

  // ---- AC4/AC7 — shadcn/ui primitives must stay generic (no workflow imports) ----
  // Scoped to src/components/ui/** (created by story 2.2; harmless until then).
  {
    files: ['src/components/ui/**/*.{ts,tsx}'],
    plugins: { 'local-rules': localRules },
    rules: {
      'local-rules/no-workflow-domain-in-ui-primitives': 'error',

      // Story 2.2 — primitives are STOCK shadcn/ui output (AC4: "used exactly as
      // shadcn provides with minimal local customization"). The following rules
      // conflict with idiomatic shadcn primitives and are relaxed ONLY for this
      // generic-primitive layer, so the files stay byte-for-byte stock and
      // 2.3/2.4 can re-skin via tokens without lint churn. Application code
      // (src/features/**, composites) keeps the full strict rule set.
      //
      //  - react/prop-types: redundant — TypeScript already types every prop.
      //  - react-refresh/only-export-components: shadcn colocates the `cva`
      //    `*Variants` export with its component by convention (DX-only rule).
      //  - strict-boolean-expressions: the `inset && 'pl-8'` className idiom uses
      //    an optional boolean; harmless in primitives.
      //  - jsx-a11y/heading-has-content: false positive on forwardRef headings
      //    (e.g. AlertTitle) whose content is always supplied by the consumer;
      //    real heading content is validated at composite/usage sites (2.15+),
      //    which live OUTSIDE src/components/ui. All other a11y rules stay ON.
      'react/prop-types': 'off',
      'react-refresh/only-export-components': 'off',
      '@typescript-eslint/strict-boolean-expressions': 'off',
      'jsx-a11y/heading-has-content': 'off',
    },
  },

  // ---- Config + tooling files: TS parser (no type-aware project), Node globals ----
  // Story 2.27 — `playwright.config.ts` (root, matched by `*.{js,ts}`) and the
  // Playwright E2E specs (`e2e/**`) lint here, NOT under the type-aware `src/**`
  // block: they live outside tsconfig.app's `include`, so a typed `projectService`
  // pass would error "file not found in project". Playwright transpiles them with
  // its own loader at run time; eslint just needs syntax + base hygiene here.
  {
    files: ['*.{js,ts}', 'tools/**/*.js'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { project: false, projectService: false },
      globals: { ...globals.node },
    },
  },

  // Playwright E2E specs (story 2.27) — TS parser, no type-aware project (they live
  // outside tsconfig.app's `include`). Both Node globals (specs run in Node) AND
  // browser globals (the `page.evaluate(() => document...)` callbacks run in the
  // page) are in scope.
  {
    files: ['e2e/**/*.{ts,tsx}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { project: false, projectService: false },
      globals: { ...globals.node, ...globals.browser },
    },
  },

  // ---- Test files: relax type-aware "unnecessary" rules (story 2.22) ----
  // Tests legitimately use defensive null-handling (`?? ''`, `?.`) and casts on
  // mocked / loosely-typed values (vi.fn, query-result mocks) that the type
  // checker deems redundant. Production code keeps the full strict rule set.
  {
    files: ['src/**/*.test.{ts,tsx}', 'src/**/__tests__/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/unbound-method': 'off',
    },
  },

  // MUST be last — turn off stylistic rules handled by Prettier (AC2).
  prettier,
);
