package org.dradgo.domain.registry;

import java.util.Map;

/**
 * Stable wire form is the explicit {@code wireValue} (decoupled from the enum constant name).
 * Renaming an enum constant must keep its {@code wireValue} identical or it is a wire-breaking
 * change.
 */
public enum DomainErrorCode implements RegistryValue {
  ILLEGAL_TRANSITION("ILLEGAL_TRANSITION"),
  IDEMPOTENCY_KEY_CONFLICT("IDEMPOTENCY_KEY_CONFLICT"),
  MISSING_IDEMPOTENCY_KEY("MISSING_IDEMPOTENCY_KEY"),
  INVALID_IDEMPOTENCY_KEY("INVALID_IDEMPOTENCY_KEY"),
  STALE_IDEMPOTENCY_RESERVATION("STALE_IDEMPOTENCY_RESERVATION"),
  IDEMPOTENCY_RESERVATION_EXHAUSTED("IDEMPOTENCY_RESERVATION_EXHAUSTED"),
  IDEMPOTENCY_RECORD_LOST("IDEMPOTENCY_RECORD_LOST"),
  EXPORT_CLASSIFICATION_VIOLATION("EXPORT_CLASSIFICATION_VIOLATION"),
  APPROVAL_VERSION_MISMATCH("APPROVAL_VERSION_MISMATCH"),
  CLARIFICATION_ARTIFACT_VERSION_MISMATCH("CLARIFICATION_ARTIFACT_VERSION_MISMATCH"),
  CLARIFICATION_NOT_FOUND("CLARIFICATION_NOT_FOUND"),
  CLARIFICATION_TERMINAL_STATE("CLARIFICATION_TERMINAL_STATE"),
  ILLEGAL_CLARIFICATION_TRANSITION("ILLEGAL_CLARIFICATION_TRANSITION"),
  CONCURRENT_TRANSITION_CONFLICT("CONCURRENT_TRANSITION_CONFLICT"),
  RUNNER_TIMEOUT("RUNNER_TIMEOUT"),
  RUNNER_CONTRACT_VIOLATION("RUNNER_CONTRACT_VIOLATION"),
  LINEAR_TICKET_NOT_FOUND("LINEAR_TICKET_NOT_FOUND"),
  INTEGRATION_LINK_CONFLICT("INTEGRATION_LINK_CONFLICT"),
  ARTIFACT_PAYLOAD_UNAVAILABLE("ARTIFACT_PAYLOAD_UNAVAILABLE"),
  ARTIFACT_LINEAGE_ALREADY_EXISTS("ARTIFACT_LINEAGE_ALREADY_EXISTS"),
  ARTIFACT_RECORD_NOT_FOUND("ARTIFACT_RECORD_NOT_FOUND"),
  ARTIFACT_OPERATION_CONFLICT("ARTIFACT_OPERATION_CONFLICT"),
  ARTIFACT_INVALID_FILENAME("ARTIFACT_INVALID_FILENAME"),
  ARTIFACT_INVALID_STATE_TRANSITION("ARTIFACT_INVALID_STATE_TRANSITION"),
  ARTIFACT_CHECKSUM_MISMATCH("ARTIFACT_CHECKSUM_MISMATCH"),
  ARTIFACT_WORKFLOW_RUN_NOT_FOUND("ARTIFACT_WORKFLOW_RUN_NOT_FOUND"),
  ARTIFACT_RUNNER_EXECUTION_TIMED_OUT("ARTIFACT_RUNNER_EXECUTION_TIMED_OUT"),
  ARTIFACT_OPERATION_INTENT_CONFLICT("ARTIFACT_OPERATION_INTENT_CONFLICT"),
  WORKFLOW_RUN_TERMINAL("WORKFLOW_RUN_TERMINAL"),
  RUNNER_EXECUTION_NOT_FOUND("RUNNER_EXECUTION_NOT_FOUND"),
  INVALID_COMMAND_PAYLOAD("INVALID_COMMAND_PAYLOAD"),
  INVALID_TIME_RANGE("INVALID_TIME_RANGE"),
  HISTORY_TOO_LARGE("HISTORY_TOO_LARGE"),
  INTERNAL_ERROR("INTERNAL_ERROR"),
  UNKNOWN_REGISTRY_VALUE("UNKNOWN_REGISTRY_VALUE"),
  INVALID_ID_PREFIX("INVALID_ID_PREFIX"),
  RUN_NOT_FOUND("RUN_NOT_FOUND"),
  UNKNOWN_ACTOR_ROLE("UNKNOWN_ACTOR_ROLE"),
  DOCTOR_POSTGRES_UNREACHABLE("DOCTOR_POSTGRES_UNREACHABLE"),
  DOCTOR_FLYWAY_FAILED("DOCTOR_FLYWAY_FAILED"),
  DOCTOR_REST_BIND_UNAVAILABLE("DOCTOR_REST_BIND_UNAVAILABLE"),
  DOCTOR_DOCKER_MISSING("DOCTOR_DOCKER_MISSING"),
  DOCTOR_CONFIG_PERMISSIONS_UNSAFE("DOCTOR_CONFIG_PERMISSIONS_UNSAFE"),
  DOCTOR_UNSUPPORTED_ENVIRONMENT("DOCTOR_UNSUPPORTED_ENVIRONMENT"),
  DOCTOR_ARTIFACT_DIR_UNWRITABLE("DOCTOR_ARTIFACT_DIR_UNWRITABLE"),
  DOCTOR_RUNNER_SECRET_MISSING("DOCTOR_RUNNER_SECRET_MISSING"),
  RETRY_NOT_APPLICABLE("RETRY_NOT_APPLICABLE");

  private static final Map<String, DomainErrorCode> LOOKUP = RegistryParsers.index(values());

  private final String wireValue;

  DomainErrorCode(String wireValue) {
    this.wireValue = wireValue;
  }

  @Override
  public String value() {
    return wireValue;
  }

  public String wireValue() {
    return wireValue;
  }

  static DomainErrorCode fromValue(String rawValue) {
    return fromValue(rawValue, null);
  }

  public static DomainErrorCode fromValue(String rawValue, String field) {
    return RegistryParsers.parse("DomainErrorCode", rawValue, field, LOOKUP);
  }
}
