/**
 * Story 2.6 (AC1, Task 1) — the typed API client.
 *
 * `openapi-fetch` gives a ~6kb fetch wrapper fully typed by the generated
 * `paths` (src/lib/api/schema.d.ts, regenerated by `npm run generate-api` from
 * 6.9's committed `openapi.json`). Hooks and the query-key factory are
 * hand-authored on top (AC3/AC6/AC8 + the `no-inline-query-keys` rule), which is
 * why `orval` was rejected — see the story's "Generator decision".
 *
 * baseUrl is the current ORIGIN (NOT the story's literal `/api/v1`): springdoc
 * emitted the operation paths with the `/api/v1` prefix already baked in
 * (`/api/v1/workflows/...`), so the client must NOT prepend it again or every
 * request would double to `/api/v1/api/v1/...`. Using `window.location.origin`
 * (rather than a bare relative `''`) yields the SAME effective same-origin URL in
 * the browser, while also being an absolute, parseable URL under the node fetch
 * the test runner uses. In dev the Vite proxy (`vite.config.ts`) forwards `/api` →
 * http://localhost:8080; in the bundled jar the SPA is served same-origin by the
 * backend — both worlds resolve to the right host.
 *
 * A single request middleware attaches the two cross-cutting headers:
 *   • X-Correlation-Id on EVERY request (story 1.19 / 2.5 seam — server logs trace
 *     back to the UI nav that triggered them).
 *   • Idempotency-Key on mutations only (story 1.9). The mutation HOOK mints a
 *     stable UUIDv7 at mutation-start and passes it through, so retries of one
 *     attempt reuse it (AC7); this middleware only mints a FALLBACK key for a
 *     mutating request that arrives without one, so the invariant ("every mutation
 *     carries an idempotency key") holds even for a caller that forgot.
 */
import createClient, { type Middleware } from 'openapi-fetch';

import { CORRELATION_ID_HEADER, newCorrelationId } from './correlation';
import { IDEMPOTENCY_KEY_HEADER, newIdempotencyKey } from './idempotency';
import { PROBLEM_JSON_CONTENT_TYPE, ProblemDetailsError, toProblemDetails } from './problemDetails';
import type { paths } from './schema';

/** HTTP methods that mutate server state and therefore need an idempotency key. */
const MUTATING_METHODS = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);

/** SEAM (story 2.6/1.19) — correlation + idempotency header attachment. */
export const headerMiddleware: Middleware = {
  onRequest({ request }) {
    if (!request.headers.has(CORRELATION_ID_HEADER)) {
      request.headers.set(CORRELATION_ID_HEADER, newCorrelationId());
    }
    if (
      MUTATING_METHODS.has(request.method.toUpperCase()) &&
      !request.headers.has(IDEMPOTENCY_KEY_HEADER)
    ) {
      request.headers.set(IDEMPOTENCY_KEY_HEADER, newIdempotencyKey());
    }
    return request;
  },
};

/** Same-origin base — see the file header for why this is origin, not `/api/v1`. */
const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';

/**
 * Defer to the LIVE global `fetch` on every call rather than letting openapi-fetch
 * capture a reference at construction time. Functionally identical in the browser,
 * but it lets the test runner's MSW interceptor (which replaces `globalThis.fetch`
 * after this module is imported) actually see the client's requests.
 */
const liveFetch: typeof globalThis.fetch = (input, init) => globalThis.fetch(input, init);

/** The single shared typed client. */
export const apiClient = createClient<paths>({ baseUrl, fetch: liveFetch });
apiClient.use(headerMiddleware);

/**
 * The shape every openapi-fetch call returns. Declared generically (`error` as
 * `unknown`, `data` as optional) ON PURPOSE: per-operation result types narrow
 * `error` to `never` for operations whose spec declares no error response (e.g.
 * `listWorkflows`, `approveSpec`), which would make the runtime guards below
 * statically dead and trip `no-unnecessary-condition`. The backend can still
 * return problem+json on those paths (a 500), so the guards must stay live — this
 * generic boundary keeps them honest.
 */
interface ApiResult<T> {
  data?: T;
  error?: unknown;
  response: Response;
}

/** Generic HTTP failure for non-problem responses such as proxy/gateway errors. */
export class HttpResponseError extends Error {
  readonly cause?: unknown;
  readonly response: Response;
  readonly status: number;

  constructor(response: Response, cause?: unknown) {
    super(`HTTP ${response.status}${response.statusText ? ` ${response.statusText}` : ''}`);
    this.name = 'HttpResponseError';
    this.response = response;
    this.status = response.status;
    this.cause = cause;
  }
}

function isProblemJsonResponse(response: Response): boolean {
  const contentType = response.headers.get('content-type') ?? '';
  return contentType.includes(PROBLEM_JSON_CONTENT_TYPE);
}

function isBodylessSuccess(response: Response): boolean {
  return response.status === 204 || response.status === 205;
}

/**
 * Unwrap an openapi-fetch result: return the typed `data` on success, or throw a
 * typed `ProblemDetailsError` built from the problem+json body on any failure.
 * Centralizes the error contract so every query/mutation fn surfaces `error.code`
 * to TanStack Query `onError` (AC5) without per-call boilerplate.
 */
export function unwrap<T>(result: ApiResult<T>): T {
  const { data, error, response } = result;
  if (response.ok && error === undefined) {
    if (data !== undefined) {
      return data;
    }
    if (isBodylessSuccess(response)) {
      return undefined as T;
    }
  }
  if (!response.ok && isProblemJsonResponse(response)) {
    throw new ProblemDetailsError(toProblemDetails(error, response.status));
  }
  if (error instanceof Error) {
    throw error;
  }
  throw new HttpResponseError(response, error);
}
