/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workflow runs
         * @description Newest-first list of workflow runs for the review queue, optionally filtered by state.
         */
        get: operations["listWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/submit-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a new workflow run */
        post: operations["submitWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workflow run detail
         * @description Current status of a single workflow run.
         */
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/approve-spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a run's specification (story 2.13 rebuild) */
        post: operations["approveSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/clarifications/{clarificationId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer an open clarification on a spec */
        post: operations["answerClarification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workflow run event history
         * @description Ordered event stream for a run, in the committed wire schema (workflow-events-response.schema.json).
         */
        get: operations["getWorkflowEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/reject-spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a run's specification (story 2.13 rebuild) */
        post: operations["rejectSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/retry-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed workflow run */
        post: operations["retryWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/takeover-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take over a workflow run */
        post: operations["takeoverWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnswerClarificationRequest: {
            answerText: string;
            artifactId: string;
            /** Format: int32 */
            expectedArtifactVersion: number;
        };
        ApproveSpecRequest: {
            artifactId: string;
            /** Format: int32 */
            expectedArtifactVersion: number;
            /** Format: int32 */
            expectedContextBundleVersion: number;
            reason?: string;
            reviewerRole?: string;
        };
        ClarificationAnswerResponse: {
            clarificationId: string;
            /** @description Clarification row status after the answer commit. Typical values follow the clarification lifecycle (open / answered / accepted / incorporated / superseded / rejected_invalid). Story 2.13 round-4 P-R4-16: idempotent replays of pre-2.13 ("legacy 2-segment") result-refs whose underlying clarification row has been hard-deleted before the replay arrived surface the sentinel value "unknown" so the previously-200 response stays 200 and the idempotent-replay contract is preserved. TS clients should default-case unknown status values rather than narrowing exhaustively. */
            clarificationStatus: string;
            correlationId?: string;
            currentState: string;
            workflowRunId: string;
        };
        LatestArtifact: {
            /** @example spec */
            artifactType?: string;
            status?: string;
            /** Format: int32 */
            version?: number;
        };
        LinkedTicket: {
            /** @example DEL-1234 */
            externalRef?: string;
            /** @example linear */
            integrationType?: string;
            syncStatus?: string;
        };
        /** @description RFC 9457 Problem Details payload with DeliveryLine extension fields. */
        ProblemDetailsResponse: {
            /** @example RUN_NOT_FOUND */
            code: string;
            /**
             * @description Echoed correlation ID when present on the request or MDC.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            correlationId?: string | null;
            /** @example Workflow run not found: run_abc123 */
            detail: string;
            /** @description Domain-specific extension payload. Validation errors emit an array of field-error objects; other domain errors typically emit an object. */
            details?: {
                [key: string]: unknown;
            } | Record<string, never>[];
            /** @example /api/v1/workflows/run_abc123/events */
            instance: string;
            /** @example false */
            retryable: boolean;
            /**
             * Format: int32
             * @example 404
             */
            status: number;
            /** @example Workflow run not found */
            title: string;
            /**
             * Format: uri
             * @example https://deliveryline.local/problems/run-not-found
             */
            type: string;
        };
        RejectSpecRequest: {
            artifactId: string;
            /** Format: int32 */
            expectedArtifactVersion: number;
            /** Format: int32 */
            expectedContextBundleVersion: number;
            reasonText: string;
            reviewerRole?: string;
            /** @enum {string} */
            taggedFeedback: "MISSING_SCOPE" | "UNCLEAR_SPECIFICATION" | "MISUNDERSTOOD_IMPLEMENTATION";
        };
        RetryWorkflowRequest: {
            actorIdentity: string;
            /** @enum {string} */
            actorType: "HUMAN" | "AGENT" | "SYSTEM" | "SERVICE_ACCOUNT";
            correlationId?: string;
            reasonText?: string;
        };
        SubmitWorkflowRequest: {
            actorIdentity: string;
            /** @enum {string} */
            actorType: "HUMAN" | "AGENT" | "SYSTEM" | "SERVICE_ACCOUNT";
            correlationId?: string;
            linearTicketReference: string;
        };
        SubmitWorkflowResponse: {
            correlationId?: string;
            currentState?: string;
            workflowRunId?: string;
        };
        TakeoverWorkflowRequest: {
            actorIdentity: string;
            /** @enum {string} */
            actorType: "HUMAN" | "AGENT" | "SYSTEM" | "SERVICE_ACCOUNT";
            correlationId?: string;
            reasonText?: string;
        };
        /** @description Current status detail of a workflow run. */
        WorkflowDetail: {
            currentActorIdentity?: string;
            currentActorType?: string;
            /** @example WaitingForSpecApproval */
            currentState?: string;
            /**
             * @description True once specRejectionLoopCount has crossed the configured escalation threshold. Informational — does NOT terminate the workflow (FR13).
             * @example false
             */
            escalationMarker?: boolean;
            failedStage?: string;
            failureCategory?: string;
            /** Format: date-time */
            failureTimestamp?: string;
            /** Format: date-time */
            lastActivityTimestamp?: string;
            /** Format: date-time */
            lastEventAt?: string;
            lastEventType?: string;
            lastSuccessfulStage?: string;
            latestArtifacts?: components["schemas"]["LatestArtifact"][];
            linkedTicket?: components["schemas"]["LinkedTicket"];
            /**
             * @description Next safe operator action for the current state.
             * @example view_only
             */
            nextSafeAction?: string;
            /**
             * Format: int32
             * @description How many spec rejections this run has accumulated. Increments on every successful rejectSpec call (story 2.10).
             * @example 0
             */
            specRejectionLoopCount?: number;
            /** @example run_abc123 */
            workflowRunId?: string;
        };
        /** @description A single workflow event. */
        WorkflowEvent: {
            actorIdentity: string;
            /**
             * @example system
             * @enum {string}
             */
            actorType: "human" | "agent" | "system" | "service_account";
            /** Format: date-time */
            createdAt: string;
            /** @description Open detail map; server-only keys (e.g. idempotencyKey) are stripped. Known keys include linearTicketReference, artifactId, artifactVersion, contextVersion, correlationId, failedStage, triggeringEventId, recoveryActionId, recoveryRetriedEventId, compensationFailed, reviewerRole, taggedFeedback, specRejectionLoopCount, escalationMarker, artifactVariant, and feedback. */
            details: {
                artifactId?: string;
                /** @enum {string} */
                artifactVariant?: "spec" | "implementationPlan" | "prOutput";
                /** Format: int32 */
                artifactVersion?: number;
                compensationFailed?: boolean;
                /** Format: int32 */
                contextVersion?: number;
                correlationId?: string;
                errorClass?: string;
                errorCode?: string;
                escalationMarker?: boolean;
                failedStage?: string;
                feedback?: string;
                linearTicketReference?: string;
                reason?: string;
                recoveryActionId?: string;
                recoveryRetriedEventId?: string;
                reviewerRole?: string;
                /** Format: int32 */
                specRejectionLoopCount?: number;
                taggedFeedback?: string;
                triggeringEventId?: string;
            } & {
                [key: string]: unknown;
            };
            /**
             * @example workflow.stateChanged
             * @enum {string}
             */
            eventType: "workflow.stateChanged" | "approval.requested" | "approval.approved" | "approval.rejected" | "escalation.required" | "artifact.draftCreated" | "artifact.available" | "artifact.failed" | "artifact.versionCreated" | "runner.started" | "runner.failed" | "recovery.retried" | "recovery.dispatchFailed" | "recovery.reconciled" | "artifact.lineageRecovered" | "integration.linked" | "export.created" | "clarification.answered" | "clarification.accepted" | "clarification.incorporated" | "clarification.superseded" | "clarification.rejectedInvalid" | "clarification.noEffectReason";
            /** @enum {string|null} */
            failureCategory?: "runner_timeout" | "runner_crash" | "runner_contract_violation" | "runner_non_zero_exit" | "runner_late_result" | "runner_duplicate_result" | "runner_malformed_output" | "orphan" | null;
            interventionMarker: boolean;
            /** @enum {string|null} */
            priorState?: "Inbox" | "Planned" | "Investigating" | "WaitingForSpecApproval" | "Executing" | "WaitingForReview" | "Completed" | "Failed" | "Paused" | "TakenOver" | "Reconciled" | null;
            /** @example evt_abc123 */
            publicId: string;
            reason?: string | null;
            /** @enum {string|null} */
            resultingState?: "Inbox" | "Planned" | "Investigating" | "WaitingForSpecApproval" | "Executing" | "WaitingForReview" | "Completed" | "Failed" | "Paused" | "TakenOver" | "Reconciled" | null;
            /** @example run_abc123 */
            workflowRunPublicId: string;
        };
        /** @description Ordered event history for a workflow run. */
        WorkflowEventsResponse: {
            events: components["schemas"]["WorkflowEvent"][];
            workflowRun: components["schemas"]["WorkflowRunRef"];
        };
        /** @description Run header for an event stream. */
        WorkflowRunRef: {
            /** Format: date-time */
            createdAt: string;
            /** @example run_abc123 */
            publicId: string;
            /**
             * @description State at the end of the returned stream (the run's current state).
             * @enum {string|null}
             */
            terminalState: "Inbox" | "Planned" | "Investigating" | "WaitingForSpecApproval" | "Executing" | "WaitingForReview" | "Completed" | "Failed" | "Paused" | "TakenOver" | "Reconciled" | null;
            /** @example DEL-1234 */
            ticketRef: string;
        };
        WorkflowStateChangeResponse: {
            correlationId?: string;
            currentState: string;
            workflowRunId: string;
        };
        /** @description Queue/list summary of a workflow run. */
        WorkflowSummary: {
            /**
             * @description Current workflow state.
             * @example WaitingForSpecApproval
             */
            currentState?: string;
            /**
             * @description True once specRejectionLoopCount has crossed the configured escalation threshold. Informational — does NOT terminate the workflow (FR13).
             * @example false
             */
            escalationMarker?: boolean;
            /**
             * Format: date-time
             * @description Timestamp of the most recent event (ISO-8601 UTC).
             */
            lastEventAt?: string;
            /**
             * @description Type of the most recent event.
             * @example workflow.stateChanged
             */
            lastEventType?: string;
            /**
             * Format: int32
             * @description How many spec rejections this run has accumulated. Increments on every successful rejectSpec call (story 2.10).
             * @example 0
             */
            specRejectionLoopCount?: number;
            /**
             * @description Linear ticket reference, if linked.
             * @example DEL-1234
             */
            ticketRef?: string;
            /**
             * @description Run public id.
             * @example run_abc123
             */
            workflowRunId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listWorkflows: {
        parameters: {
            query?: {
                /** @description Optional current-state filter, e.g. WaitingForSpecApproval. */
                state?: string;
                /** @description Max rows to return (clamped to 1..200). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow run summaries (direct array, no envelope). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowSummary"][];
                };
            };
        };
    };
    submitWorkflow: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitWorkflowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitWorkflowResponse"];
                };
            };
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Run public id, e.g. run_abc123.
                 * @example run_abc123
                 */
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow run detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetail"];
                };
            };
            /** @description Malformed run id (INVALID_ID_PREFIX). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description No such run (RUN_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    approveSpec: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveSpecRequest"];
            };
        };
        responses: {
            /** @description Approval recorded; state advanced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, INVALID_ID_PREFIX. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description RUN_NOT_FOUND or ARTIFACT_RECORD_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description APPROVAL_VERSION_MISMATCH, IDEMPOTENCY_KEY_CONFLICT, ILLEGAL_TRANSITION, or WORKFLOW_RUN_TERMINAL. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description ARTIFACT_PAYLOAD_UNAVAILABLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    answerClarification: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                workflowRunId: string;
                clarificationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerClarificationRequest"];
            };
        };
        responses: {
            /** @description Answer recorded against the clarification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationAnswerResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, INVALID_ID_PREFIX. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description RUN_NOT_FOUND, CLARIFICATION_NOT_FOUND, or ARTIFACT_RECORD_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description CLARIFICATION_ARTIFACT_VERSION_MISMATCH, CLARIFICATION_TERMINAL_STATE, ILLEGAL_CLARIFICATION_TRANSITION, IDEMPOTENCY_KEY_CONFLICT, or WORKFLOW_RUN_TERMINAL. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    getWorkflowEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Run public id, e.g. run_abc123.
                 * @example run_abc123
                 */
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEventsResponse"];
                };
            };
            /** @description Malformed run id (INVALID_ID_PREFIX) or history too large. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description No such run (RUN_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    rejectSpec: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectSpecRequest"];
            };
        };
        responses: {
            /** @description Rejection recorded; state advanced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, INVALID_ID_PREFIX. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description RUN_NOT_FOUND or ARTIFACT_RECORD_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description APPROVAL_VERSION_MISMATCH, IDEMPOTENCY_KEY_CONFLICT, ILLEGAL_TRANSITION, or WORKFLOW_RUN_TERMINAL. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description ARTIFACT_PAYLOAD_UNAVAILABLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    retryWorkflow: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryWorkflowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
        };
    };
    takeoverWorkflow: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakeoverWorkflowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
        };
    };
}
