/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project */
        get: operations["getProject"];
        /** Edit a project's mutable configuration */
        put: operations["updateProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/credentials/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set or rotate a connector credential (write-only — never returned) */
        put: operations["setProjectCredential"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft-disable a project (the default project cannot be disabled) */
        post: operations["disableProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-enable a disabled project (status := ACTIVE) */
        post: operations["enableProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run capability-aware connectivity probes (per-check results, HTTP 200) */
        post: operations["testProjectConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runner-queue/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runner worker-pool state, queue depth, oldest-queued age, stale counts, and per-worker current work. Optional batchId scopes the counts + workers to one batch. */
        get: operations["getRunnerQueueStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workflow runs
         * @description Newest-first list of workflow runs for the review queue, optionally filtered by state.
         */
        get: operations["listWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a batch of workflow tickets (best-effort, per-ticket outcomes) */
        post: operations["submitBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/submit-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a new workflow run */
        post: operations["submitWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workflow run detail
         * @description Current status of a single workflow run.
         */
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/accept-implementation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a run's implementation (story 3.23) */
        post: operations["acceptImplementation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/allowed-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get backend-derived allowed actions for a workflow run
         * @description Returns the typed list of actions valid for the run's current state + actor role, plus a version stamp the UI echoes back on mutations to detect staleness (story 2.14). Read-only and idempotent — no Idempotency-Key required. Forward-compatible: the UI must gracefully hide unknown action values (UX-DR12, UX-DR6).
         */
        get: operations["getAllowedActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/approve-spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a run's specification (story 2.13 rebuild) */
        post: operations["approveSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/artifacts/{artifactId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a workflow artifact's redacted content
         * @description Returns the redacted payload (UTF-8 markdown body) and metadata of a single artifact owned by the run. Backs the Artifact Review Panel spec read (story 3a-9).
         */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/clarifications/{clarificationId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer an open clarification on a spec */
        post: operations["answerClarification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workflow run event history
         * @description Ordered event stream for a run, in the committed wire schema (workflow-events-response.schema.json).
         */
        get: operations["getWorkflowEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/reject-implementation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a run's implementation with structured technical feedback (story 3.24) */
        post: operations["rejectImplementation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/reject-spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a run's specification (story 2.13 rebuild) */
        post: operations["rejectSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/retry-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed workflow run */
        post: operations["retryWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/runner-logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a run's latest runner-execution logs (live + historical)
         * @description Server-Sent Events stream of the run's latest runner execution. While the execution is live the container's logs are followed (docker logs --follow) with BEST-EFFORT per-line redaction; once finished, the persisted post-hoc-redacted log (story 3.6) is replayed — that persisted scan is the AUTHORITATIVE redaction guarantee, the live redaction is best-effort only (ADR 0025). Served only over the localhost-only binding to the single local operator; gated by the view_runner_logs allowed-action. Persists nothing and never mutates runner_executions (ADR 0025 D4). Epic 4 story 4.4 consumes this same viewer (no separate redacted-log download surface). Events: log {stream,line,seq}, status {phase,rex}, end {reason}, error {reason}.
         */
        get: operations["streamRunnerLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/takeover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take over a workflow run for manual developer continuation (story 3.25)
         * @description Stops orchestrator dispatch, cancels all in-flight + queued runner executions, records a developer takeover, and transitions the run to the TakenOver terminal state while preserving all prior context (artifacts, audit trail, and the active GitHub PR link). This action is non-reversible in E3 — Epic 4 will add takeover-revert; until then, a taken-over run can only be closed by an operator action.
         */
        post: operations["takeover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflowRunId}/takeover-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take over a workflow run */
        post: operations["takeoverWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptImplementationRequest: {
            artifactId: string;
            /** Format: int32 */
            expectedArtifactVersion: number;
            /** Format: int32 */
            expectedContextBundleVersion: number;
            reason?: string;
            reviewerRole?: string;
        };
        /** @description Backend-derived list of allowed actions for the current state + actor role. */
        AllowedActions: {
            /**
             * @description Typed action wire values. Primary action first (e.g. approve_spec before reject_spec), then passive views. UI must gracefully ignore unknown values for forward compatibility (UX-DR12, UX-DR6).
             * @example [
             *       "approve_spec",
             *       "reject_spec",
             *       "answer_clarification"
             *     ]
             */
            actions: string[];
            /** @description Version stamp the UI echoes back as expectedAllowedActionsVersionStamp on the next mutation so a stale UI surfaces APPROVAL_VERSION_MISMATCH. */
            versionStamp: components["schemas"]["AllowedActionsVersionStamp"];
        };
        /** @description Version stamp the UI echoes back on mutations so stale UI surfaces a typed version-mismatch error. */
        AllowedActionsVersionStamp: {
            /**
             * Format: int32
             * @description Context-bundle version of the latest spec's runner execution; null if absent.
             * @example 1
             */
            currentContextBundleVersion?: number | null;
            /**
             * Format: int32
             * @description Version of the LATEST spec artifact (any approval status); null if none.
             * @example 1
             */
            currentSpecArtifactVersion?: number | null;
            /**
             * @description Public id of the most recent workflow event; null on event-less runs.
             * @example evt_abc123
             */
            lastEventId?: string | null;
            /**
             * @description Current workflow state (wire-string form).
             * @example WaitingForSpecApproval
             */
            workflowState: string;
        };
        AnswerClarificationRequest: {
            answerText: string;
            artifactId: string;
            /** Format: int32 */
            expectedArtifactVersion: number;
        };
        ApproveSpecRequest: {
            artifactId: string;
            /** Format: int32 */
            expectedArtifactVersion: number;
            /** Format: int32 */
            expectedContextBundleVersion: number;
            reason?: string;
            reviewerRole?: string;
        };
        /** @description Redacted content of a single workflow artifact. */
        ArtifactDetail: {
            /** @example art_abc123 */
            artifactId?: string;
            /** @example spec */
            artifactType?: string;
            /**
             * @description Redacted artifact payload as a UTF-8 markdown string (not base64). Empty for a prOutput (its content travels in the structured fields below).
             * @example # Specification
             *
             *     ...
             */
            body?: string;
            /**
             * @description prOutput only: the pushed branch name; null for spec/implementationPlan.
             * @example feature/x
             */
            branch?: string | null;
            /**
             * @description Short-form checksum (<algorithm>:<first 12 hex>); null when unset.
             * @example SHA-256:9f86d081884c
             */
            checksum?: string;
            /** @example shareable-redacted */
            classification?: string;
            /**
             * @description prOutput only: the pushed commit SHA; null otherwise.
             * @example abcdef1234567890abcdef1234567890abcdef12
             */
            commitSha?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** @description prOutput only: the unified diff (size-capped) resolved at ingest; null when the runner produced no resolvable diff. */
            diff?: string | null;
            /**
             * @description prOutput only: the canonical PR reference (org/repo#n) from the active github_pr link (co-present with prState); null when no linked PR.
             * @example octo/hello#42
             */
            prReference?: string | null;
            /**
             * @description prOutput only: the PR state from the active github_pr link (draft/open/merged/closed), co-present with prReference; null when no linked PR.
             * @example open
             */
            prState?: string | null;
            /** @example available */
            status?: string;
            /** @description implementationPlan only: the ordered plan steps parsed from the payload; null for spec/prOutput. */
            steps?: string[] | null;
            /**
             * Format: int32
             * @example 3
             */
            version?: number;
        };
        BatchSubmissionRequest: {
            actorIdentity: string;
            /** @enum {string} */
            actorType: "HUMAN" | "AGENT" | "SYSTEM" | "SERVICE_ACCOUNT";
            correlationId?: string;
            linearTicketReferences: string[];
        };
        BatchSubmissionResponse: {
            actorIdentity: string;
            batchId: string;
            /** Format: int32 */
            queuedCount: number;
            /** Format: int32 */
            rejectedCount: number;
            submittedAt: string;
            tickets: components["schemas"]["TicketResult"][];
            /** Format: int32 */
            total: number;
        };
        ClarificationAnswerResponse: {
            clarificationId: string;
            /** @description Clarification row status after the answer commit. Typical values follow the clarification lifecycle (open / answered / accepted / incorporated / superseded / rejected_invalid). Story 2.13 round-4 P-R4-16: idempotent replays of pre-2.13 ("legacy 2-segment") result-refs whose underlying clarification row has been hard-deleted before the replay arrived surface the sentinel value "unknown" so the previously-200 response stays 200 and the idempotent-replay contract is preserved. TS clients should default-case unknown status values rather than narrowing exhaustively. */
            clarificationStatus: string;
            correlationId?: string;
            currentState: string;
            workflowRunId: string;
        };
        /** @description One connectivity check's tri-state result. */
        ConnectionCheckResult: {
            /**
             * @description Which check.
             * @example repository_reachable
             * @enum {string}
             */
            check?: "repository_reachable" | "ticket_source_auth" | "repository_host_auth";
            /**
             * @description Secret-free human detail.
             * @example authenticated
             */
            detail?: string;
            /**
             * @description Tri-state outcome.
             * @example pass
             * @enum {string}
             */
            status?: "pass" | "fail" | "skipped";
        };
        /** @description Create a new project. */
        CreateProjectRequest: {
            /** @example Acme Widgets */
            name: string;
            /**
             * @description Whether OpenSpec is enabled.
             * @example false
             */
            openspecEnabled?: boolean;
            /** @example github */
            repoHostKind: string;
            /** @example https://github.com/acme/widgets */
            repositoryUrl?: string | null;
            /**
             * @description Optional per-project runner override; null uses defaults.
             * @enum {string|null}
             */
            runnerKind?: "manual" | "codex" | "claude" | null;
            /** @example acme-widgets */
            slug: string;
            /** @example linear */
            ticketSourceKind: string;
        };
        /** @description Per-role credential presence (never the value). */
        CredentialPresence: {
            /**
             * @description Connector role.
             * @example ticket_source
             */
            role?: string;
            /**
             * @description Whether a credential is configured for this role.
             * @example configured
             * @enum {string}
             */
            status?: "configured" | "not_configured";
        };
        LatestArtifact: {
            /**
             * @description Public id of this latest artifact. Resolves the artifact-read endpoint (GET .../artifacts/{artifactId}) and the spec approval/decision bar (story 2.19 resolveSpecArtifactId).
             * @example art_abc123
             */
            artifactId?: string;
            /** @example spec */
            artifactType?: string;
            status?: string;
            /** Format: int32 */
            version?: number;
        };
        LinkedTicket: {
            /** @example DEL-1234 */
            externalRef?: string;
            /** @example linear */
            integrationType?: string;
            syncStatus?: string;
        };
        /** @description RFC 9457 Problem Details payload with DeliveryLine extension fields. */
        ProblemDetailsResponse: {
            /** @example RUN_NOT_FOUND */
            code: string;
            /**
             * @description Echoed correlation ID when present on the request or MDC.
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            correlationId?: string | null;
            /** @example Workflow run not found: run_abc123 */
            detail: string;
            /** @description Domain-specific extension payload. Validation errors emit an array of field-error objects; other domain errors typically emit an object. */
            details?: {
                [key: string]: unknown;
            } | Record<string, never>[];
            /** @example /api/v1/workflows/run_abc123/events */
            instance: string;
            /** @example false */
            retryable: boolean;
            /**
             * Format: int32
             * @example 404
             */
            status: number;
            /** @example Workflow run not found */
            title: string;
            /**
             * Format: uri
             * @example https://deliveryline.local/problems/run-not-found
             */
            type: string;
        };
        /** @description A configured project (never carries a credential value). */
        Project: {
            /**
             * @description Backend-derived actions valid for this project's current status. The UI must gracefully ignore unknown values for forward compatibility.
             * @example [
             *       "edit",
             *       "disable",
             *       "set_credential",
             *       "test_connection"
             *     ]
             */
            allowedActions?: string[];
            /**
             * Format: date-time
             * @description Creation timestamp (UTC).
             */
            createdAt?: string;
            /** @description Per-role credential presence (never the value). */
            credentials?: components["schemas"]["CredentialPresence"][];
            /**
             * @description Project public id.
             * @example prj_abc123
             */
            id?: string;
            /**
             * @description Human-readable project name.
             * @example Acme Widgets
             */
            name?: string;
            /** @description Whether OpenSpec is enabled for this project. */
            openspecEnabled?: boolean;
            /**
             * @description Repository-host connector kind.
             * @example github
             */
            repoHostKind?: string;
            /**
             * @description Repository URL (nullable).
             * @example https://github.com/acme/widgets
             */
            repositoryUrl?: string | null;
            /**
             * @description Per-project runner override; null uses defaults.
             * @enum {string|null}
             */
            runnerKind?: "manual" | "codex" | "claude" | null;
            /**
             * @description Stable URL/CLI slug.
             * @example acme-widgets
             */
            slug?: string;
            /**
             * @description Project status.
             * @example active
             * @enum {string}
             */
            status?: "active" | "disabled";
            /**
             * @description Ticket-source connector kind.
             * @example linear
             */
            ticketSourceKind?: string;
        };
        RejectImplementationRequest: {
            artifactId: string;
            /** Format: int32 */
            expectedArtifactVersion: number;
            /** Format: int32 */
            expectedContextBundleVersion: number;
            reasonText: string;
            reviewerRole?: string;
            /** @enum {string} */
            taggedFeedback: "MISSING_SCOPE" | "UNCLEAR_SPECIFICATION" | "MISUNDERSTOOD_IMPLEMENTATION" | "INCORRECT_APPROACH" | "INCOMPLETE_IMPLEMENTATION" | "QUALITY_ISSUE" | "BREAKS_EXISTING_FUNCTIONALITY" | "OUT_OF_SCOPE";
        };
        RejectSpecRequest: {
            artifactId: string;
            /** Format: int32 */
            expectedArtifactVersion: number;
            /** Format: int32 */
            expectedContextBundleVersion: number;
            reasonText: string;
            reviewerRole?: string;
            /** @enum {string} */
            taggedFeedback: "MISSING_SCOPE" | "UNCLEAR_SPECIFICATION" | "MISUNDERSTOOD_IMPLEMENTATION" | "INCORRECT_APPROACH" | "INCOMPLETE_IMPLEMENTATION" | "QUALITY_ISSUE" | "BREAKS_EXISTING_FUNCTIONALITY" | "OUT_OF_SCOPE";
        };
        RetryWorkflowRequest: {
            actorIdentity: string;
            /** @enum {string} */
            actorType: "HUMAN" | "AGENT" | "SYSTEM" | "SERVICE_ACCOUNT";
            correlationId?: string;
            reasonText?: string;
        };
        RunnerQueueStatusResponse: {
            /** Format: int64 */
            activeWorkers: number;
            /** Format: int64 */
            idleWorkers: number;
            /** Format: int64 */
            inFlightExecutions: number;
            /** Format: int64 */
            oldestQueuedAgeSeconds: number;
            oldestQueuedAt?: string;
            /** Format: int32 */
            poolSize: number;
            /** Format: int64 */
            queueDepth: number;
            /** Format: int64 */
            recentThroughputPerMinute: number;
            /** Format: int64 */
            staleDispatchedCount: number;
            /** Format: int64 */
            staleQueuedCount: number;
            workers: components["schemas"]["WorkerStatusResponse"][];
        };
        /** @description Set or rotate a connector credential. */
        SetCredentialRequest: {
            /** @description The plaintext connector credential. Write-only — never returned. */
            secret: string;
        };
        /** @description Non-secret credential-set confirmation. */
        SetCredentialResponse: {
            /**
             * @description Non-secret credential public id.
             * @example cred_abc123
             */
            credentialId?: string;
            /** @example ticket_source */
            role?: string;
            /** @example configured */
            status?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        SubmitWorkflowRequest: {
            actorIdentity: string;
            /** @enum {string} */
            actorType: "HUMAN" | "AGENT" | "SYSTEM" | "SERVICE_ACCOUNT";
            correlationId?: string;
            linearTicketReference: string;
            projectReference?: string;
        };
        SubmitWorkflowResponse: {
            correlationId?: string;
            currentState?: string;
            workflowRunId?: string;
        };
        TakeoverRequest: {
            reasonText: string;
            reviewerRole?: string;
        };
        TakeoverResponse: {
            /** Format: int32 */
            cancelledInFlightCount?: number;
            /** Format: int32 */
            cancelledQueuedCount?: number;
            correlationId?: string;
            currentState: string;
            preservedPrReference?: string;
            recoveryActionId: string;
            replayed: boolean;
            workflowRunId: string;
        };
        TakeoverWorkflowRequest: {
            actorIdentity: string;
            /** @enum {string} */
            actorType: "HUMAN" | "AGENT" | "SYSTEM" | "SERVICE_ACCOUNT";
            correlationId?: string;
            reasonText?: string;
        };
        /** @description Per-check connectivity probe results (HTTP 200). */
        TestConnection: {
            /** @description One result per connectivity check. */
            checks?: components["schemas"]["ConnectionCheckResult"][];
        };
        TicketResult: {
            /** @enum {string} */
            queueResult: "queued" | "rejected";
            rejectionCode?: string;
            rejectionReason?: string;
            runId?: string;
            ticketRef: string;
        };
        /** @description Edit a project's mutable configuration. */
        UpdateProjectRequest: {
            /** @example Acme Widgets */
            name: string;
            /**
             * @description Whether OpenSpec is enabled.
             * @example false
             */
            openspecEnabled?: boolean;
            /** @example github */
            repoHostKind: string;
            /** @example https://github.com/acme/widgets */
            repositoryUrl?: string | null;
            /**
             * @description Optional per-project runner override; null uses defaults.
             * @enum {string|null}
             */
            runnerKind?: "manual" | "codex" | "claude" | null;
            /** @example linear */
            ticketSourceKind: string;
        };
        WorkerStatusResponse: {
            currentRunnerExecutionId?: string;
            currentStage?: string;
            currentWorkflowRunId?: string;
            dispatchedAt?: string;
            state: string;
            workerId: string;
        };
        /** @description Current status detail of a workflow run. */
        WorkflowDetail: {
            currentActorIdentity?: string;
            currentActorType?: string;
            /** @example WaitingForSpecApproval */
            currentState?: string;
            /**
             * @description True once specRejectionLoopCount has crossed the configured escalation threshold. Informational — does NOT terminate the workflow (FR13).
             * @example false
             */
            escalationMarker?: boolean;
            failedStage?: string;
            failureCategory?: string;
            /** Format: date-time */
            failureTimestamp?: string;
            /** Format: date-time */
            lastActivityTimestamp?: string;
            /** Format: date-time */
            lastEventAt?: string;
            lastEventType?: string;
            lastSuccessfulStage?: string;
            latestArtifacts?: components["schemas"]["LatestArtifact"][];
            linkedTicket?: components["schemas"]["LinkedTicket"];
            /**
             * @description Next safe operator action for the current state.
             * @example view_only
             */
            nextSafeAction?: string;
            /**
             * Format: int32
             * @description How many spec rejections this run has accumulated. Increments on every successful rejectSpec call (story 2.10).
             * @example 0
             */
            specRejectionLoopCount?: number;
            /** @example run_abc123 */
            workflowRunId?: string;
        };
        /** @description A single workflow event. */
        WorkflowEvent: {
            actorIdentity: string;
            /**
             * @example system
             * @enum {string}
             */
            actorType: "human" | "agent" | "system" | "service_account";
            /** Format: date-time */
            createdAt: string;
            /** @description Open detail map; server-only keys (e.g. idempotencyKey) are stripped. Known keys include linearTicketReference, artifactId, artifactVersion, contextVersion, correlationId, failedStage, triggeringEventId, recoveryActionId, recoveryRetriedEventId, compensationFailed, reviewerRole, taggedFeedback, specRejectionLoopCount, escalationMarker, artifactVariant, and feedback. */
            details: {
                artifactId?: string;
                /** @enum {string} */
                artifactVariant?: "spec" | "implementationPlan" | "prOutput";
                /** Format: int32 */
                artifactVersion?: number;
                compensationFailed?: boolean;
                /** Format: int32 */
                contextVersion?: number;
                correlationId?: string;
                errorClass?: string;
                errorCode?: string;
                escalationMarker?: boolean;
                failedStage?: string;
                feedback?: string;
                linearTicketReference?: string;
                reason?: string;
                recoveryActionId?: string;
                recoveryRetriedEventId?: string;
                reviewerRole?: string;
                /** Format: int32 */
                specRejectionLoopCount?: number;
                taggedFeedback?: string;
                triggeringEventId?: string;
            } & {
                [key: string]: unknown;
            };
            /**
             * @example workflow.stateChanged
             * @enum {string}
             */
            eventType: "workflow.stateChanged" | "approval.requested" | "approval.approved" | "approval.rejected" | "escalation.required" | "artifact.draftCreated" | "artifact.available" | "artifact.failed" | "artifact.versionCreated" | "runner.started" | "runner.failed" | "runner.dispatched" | "runner.heartbeatStale" | "runner.timeout" | "runner.orphaned" | "runner.completed" | "recovery.retried" | "recovery.dispatchFailed" | "recovery.reconciled" | "artifact.lineageRecovered" | "integration.linked" | "export.created" | "clarification.answered" | "clarification.accepted" | "clarification.incorporated" | "clarification.superseded" | "clarification.rejectedInvalid" | "clarification.noEffectReason";
            /** @enum {string|null} */
            failureCategory?: "runner_timeout" | "runner_crash" | "runner_contract_violation" | "runner_non_zero_exit" | "runner_late_result" | "runner_duplicate_result" | "runner_malformed_output" | "runner_secret_leak" | "orphan" | null;
            interventionMarker: boolean;
            /** @enum {string|null} */
            priorState?: "Inbox" | "Planned" | "Investigating" | "WaitingForSpecApproval" | "Executing" | "WaitingForReview" | "Completed" | "Failed" | "Paused" | "TakenOver" | "Reconciled" | null;
            /** @example evt_abc123 */
            publicId: string;
            reason?: string | null;
            /** @enum {string|null} */
            resultingState?: "Inbox" | "Planned" | "Investigating" | "WaitingForSpecApproval" | "Executing" | "WaitingForReview" | "Completed" | "Failed" | "Paused" | "TakenOver" | "Reconciled" | null;
            /** @example run_abc123 */
            workflowRunPublicId: string;
        };
        /** @description Ordered event history for a workflow run. */
        WorkflowEventsResponse: {
            events: components["schemas"]["WorkflowEvent"][];
            workflowRun: components["schemas"]["WorkflowRunRef"];
        };
        /** @description Run header for an event stream. */
        WorkflowRunRef: {
            /** Format: date-time */
            createdAt: string;
            /** @example run_abc123 */
            publicId: string;
            /**
             * @description State at the end of the returned stream (the run's current state).
             * @enum {string|null}
             */
            terminalState: "Inbox" | "Planned" | "Investigating" | "WaitingForSpecApproval" | "Executing" | "WaitingForReview" | "Completed" | "Failed" | "Paused" | "TakenOver" | "Reconciled" | null;
            /** @example DEL-1234 */
            ticketRef: string;
        };
        WorkflowStateChangeResponse: {
            correlationId?: string;
            currentState: string;
            workflowRunId: string;
        };
        /** @description Queue/list summary of a workflow run. */
        WorkflowSummary: {
            /**
             * @description Current workflow state.
             * @example WaitingForSpecApproval
             */
            currentState?: string;
            /**
             * @description True once specRejectionLoopCount has crossed the configured escalation threshold. Informational — does NOT terminate the workflow (FR13).
             * @example false
             */
            escalationMarker?: boolean;
            /**
             * Format: date-time
             * @description Timestamp of the most recent event (ISO-8601 UTC).
             */
            lastEventAt?: string;
            /**
             * @description Type of the most recent event.
             * @example workflow.stateChanged
             */
            lastEventType?: string;
            /**
             * Format: int32
             * @description How many spec rejections this run has accumulated. Increments on every successful rejectSpec call (story 2.10).
             * @example 0
             */
            specRejectionLoopCount?: number;
            /**
             * @description Linear ticket reference, if linked.
             * @example DEL-1234
             */
            ticketRef?: string;
            /**
             * @description Run public id.
             * @example run_abc123
             */
            workflowRunId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects (direct array, no envelope). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
                "X-Actor-Identity"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description INVALID_COMMAND_PAYLOAD or UNKNOWN_REGISTRY_VALUE (bad connector kind). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description PROJECT_SLUG_CONFLICT or IDEMPOTENCY_KEY_CONFLICT. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description PROJECT_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: {
                "X-Actor-Identity"?: string;
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description INVALID_COMMAND_PAYLOAD or UNKNOWN_REGISTRY_VALUE (bad connector kind). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description PROJECT_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description PROJECT_SLUG_CONFLICT. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    setProjectCredential: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                projectId: string;
                /**
                 * @description Connector role (underscored wire form).
                 * @example ticket_source
                 */
                role: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCredentialRequest"];
            };
        };
        responses: {
            /** @description Credential configured (non-secret id only). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetCredentialResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, or UNKNOWN_REGISTRY_VALUE (bad role). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description PROJECT_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description IDEMPOTENCY_KEY_CONFLICT. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description CREDENTIAL_MASTER_KEY_UNCONFIGURED (no master key configured). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    disableProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project disabled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description INVALID_COMMAND_PAYLOAD (the default project cannot be disabled). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description PROJECT_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    enableProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project enabled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description PROJECT_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    testProjectConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-check connectivity results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnection"];
                };
            };
            /** @description UNSUPPORTED_CONNECTOR_KIND (a project kind has no registered adapter). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description PROJECT_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    getRunnerQueueStatus: {
        parameters: {
            query?: {
                /** @description Scope queue depth + workers to one batch (bat_...) */
                batchId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current runner-queue + worker-pool status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerQueueStatusResponse"];
                };
            };
            /** @description INVALID_ID_PREFIX — the supplied batchId is not a bat_ public id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    listWorkflows: {
        parameters: {
            query?: {
                /** @description Optional current-state filter, e.g. WaitingForSpecApproval. */
                state?: string;
                /** @description Max rows to return (clamped to 1..200). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow run summaries (direct array, no envelope). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowSummary"][];
                };
            };
        };
    };
    submitBatch: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSubmissionRequest"];
            };
        };
        responses: {
            /** @description Batch accepted; body carries per-ticket queued/rejected outcomes (a rejected ticket does NOT make the batch non-2xx). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSubmissionResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, or INVALID_COMMAND_PAYLOAD (empty list, oversize, or above the configured batch maximum). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description IDEMPOTENCY_KEY_CONFLICT (same key, different fingerprint). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    submitWorkflow: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitWorkflowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitWorkflowResponse"];
                };
            };
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Run public id, e.g. run_abc123.
                 * @example run_abc123
                 */
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow run detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetail"];
                };
            };
            /** @description Malformed run id (INVALID_ID_PREFIX). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description No such run (RUN_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    acceptImplementation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptImplementationRequest"];
            };
        };
        responses: {
            /** @description Acceptance recorded; state advanced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, INVALID_ID_PREFIX, INVALID_REVIEWER_ROLE_FOR_ENDPOINT. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description RUN_NOT_FOUND or ARTIFACT_RECORD_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description APPROVAL_VERSION_MISMATCH, IDEMPOTENCY_KEY_CONFLICT, ARTIFACT_PR_LINK_MISMATCH, ILLEGAL_TRANSITION, or WORKFLOW_RUN_TERMINAL. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description ARTIFACT_PAYLOAD_UNAVAILABLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    getAllowedActions: {
        parameters: {
            query?: {
                /**
                 * @description Actor role for action gating; defaults to product_reviewer when absent. Recognized values are case-sensitive — any other value returns 400 UNKNOWN_ACTOR_ROLE.
                 * @example product_reviewer
                 */
                actorRole?: "product_reviewer" | "workflow_owner" | "developer";
            };
            header?: never;
            path: {
                /**
                 * @description Run public id, e.g. run_abc123.
                 * @example run_abc123
                 */
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Allowed actions + version stamp. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowedActions"];
                };
            };
            /** @description Malformed run id (INVALID_ID_PREFIX) or unrecognized actorRole (UNKNOWN_ACTOR_ROLE). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description No such run (RUN_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    approveSpec: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveSpecRequest"];
            };
        };
        responses: {
            /** @description Approval recorded; state advanced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, INVALID_ID_PREFIX. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description RUN_NOT_FOUND or ARTIFACT_RECORD_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description APPROVAL_VERSION_MISMATCH, IDEMPOTENCY_KEY_CONFLICT, ILLEGAL_TRANSITION, or WORKFLOW_RUN_TERMINAL. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description ARTIFACT_PAYLOAD_UNAVAILABLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Run public id, e.g. run_abc123.
                 * @example run_abc123
                 */
                workflowRunId: string;
                /**
                 * @description Artifact public id, e.g. art_abc123.
                 * @example art_abc123
                 */
                artifactId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact content + metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetail"];
                };
            };
            /** @description Malformed run or artifact id (INVALID_ID_PREFIX). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description No such run (RUN_NOT_FOUND) or no such artifact for this run (ARTIFACT_RECORD_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description Artifact payload could not be read (ARTIFACT_PAYLOAD_UNAVAILABLE). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    answerClarification: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                workflowRunId: string;
                clarificationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerClarificationRequest"];
            };
        };
        responses: {
            /** @description Answer recorded against the clarification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationAnswerResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, INVALID_ID_PREFIX. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description RUN_NOT_FOUND, CLARIFICATION_NOT_FOUND, or ARTIFACT_RECORD_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description CLARIFICATION_ARTIFACT_VERSION_MISMATCH, CLARIFICATION_TERMINAL_STATE, ILLEGAL_CLARIFICATION_TRANSITION, IDEMPOTENCY_KEY_CONFLICT, or WORKFLOW_RUN_TERMINAL. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    getWorkflowEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Run public id, e.g. run_abc123.
                 * @example run_abc123
                 */
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEventsResponse"];
                };
            };
            /** @description Malformed run id (INVALID_ID_PREFIX) or history too large. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description No such run (RUN_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    rejectImplementation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectImplementationRequest"];
            };
        };
        responses: {
            /** @description Rejection recorded; state advanced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, INVALID_ID_PREFIX, INVALID_REVIEWER_ROLE_FOR_ENDPOINT, INVALID_REJECTION_TAXONOMY, MISSING_REJECTION_TAXONOMY. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description RUN_NOT_FOUND or ARTIFACT_RECORD_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description APPROVAL_VERSION_MISMATCH, IDEMPOTENCY_KEY_CONFLICT, ILLEGAL_TRANSITION, or WORKFLOW_RUN_TERMINAL. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    rejectSpec: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectSpecRequest"];
            };
        };
        responses: {
            /** @description Rejection recorded; state advanced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, INVALID_ID_PREFIX. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description RUN_NOT_FOUND or ARTIFACT_RECORD_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description APPROVAL_VERSION_MISMATCH, IDEMPOTENCY_KEY_CONFLICT, ILLEGAL_TRANSITION, or WORKFLOW_RUN_TERMINAL. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description ARTIFACT_PAYLOAD_UNAVAILABLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    retryWorkflow: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryWorkflowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
        };
    };
    streamRunnerLogs: {
        parameters: {
            query?: {
                /**
                 * @description Actor role for action gating; defaults to product_reviewer when absent. view_runner_logs is role-agnostic in the runner-execution states, so the default resolves the gate for any operator.
                 * @example product_reviewer
                 */
                actorRole?: "product_reviewer" | "workflow_owner" | "developer";
            };
            header?: never;
            path: {
                /**
                 * @description Run public id, e.g. run_abc123.
                 * @example run_abc123
                 */
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream (text/event-stream). When view_runner_logs is not allowed for the run's state, the stream carries a single error+end event instead of log lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
            /** @description Malformed run id (INVALID_ID_PREFIX) or unrecognized actorRole. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description No such run (RUN_NOT_FOUND). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    takeover: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Actor-Identity"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakeoverRequest"];
            };
        };
        responses: {
            /** @description Takeover recorded; run is now TakenOver. This action is non-reversible in E3 — Epic 4 will add takeover-revert; until then, a taken-over run can only be closed by an operator action. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TakeoverResponse"];
                };
            };
            /** @description MISSING_IDEMPOTENCY_KEY, INVALID_IDEMPOTENCY_KEY, INVALID_COMMAND_PAYLOAD, INVALID_REVIEWER_ROLE_FOR_ENDPOINT. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description RUN_NOT_FOUND. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
            /** @description IDEMPOTENCY_KEY_CONFLICT, ILLEGAL_TRANSITION, or WORKFLOW_RUN_TERMINAL. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsResponse"];
                };
            };
        };
    };
    takeoverWorkflow: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                workflowRunId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakeoverWorkflowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStateChangeResponse"];
                };
            };
        };
    };
}
