package org.dradgo.runnercontracts;

public enum ValidationErrorCode {
	SCHEMA_VALIDATION_FAILED,
	JSON_PARSE_FAILED,
	DUPLICATE_RUNNER_EXECUTION_ID,
	STALE_METADATA,
	FILE_TOO_LARGE,
	PATH_TRAVERSAL_DETECTED,
	METADATA_SPOOFING_DETECTED
}
