package org.dradgo.adapters.cli;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import org.dradgo.application.workflow.SubmitWorkflowResult;
import org.dradgo.application.workflow.WorkflowCommandService;
import org.dradgo.application.workflow.commands.SubmitWorkflowCommand;
import org.dradgo.domain.DomainException;
import org.dradgo.domain.registry.ActorType;
import org.dradgo.domain.registry.DomainErrorCode;
import org.dradgo.domain.registry.WorkflowState;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

class WorkflowCommandsTest {

	@Test
	void interactiveSubmitAutoGeneratesUuidV7WhenKeyIsOmitted() {
		WorkflowCommandService service = mock(WorkflowCommandService.class);
		when(service.submit(any())).thenReturn(new SubmitWorkflowResult(
			"run_submit1234",
			WorkflowState.INBOX,
			"corr-submit-1"));
		WorkflowCommands commands = new WorkflowCommands(
			service,
			() -> true,
			() -> "01964c38-1c45-7000-8000-000000000000");

		String output = commands.submit(
			"LIN-123",
			"alex",
			ActorType.HUMAN,
			null,
			"corr-submit-1",
			true);

		ArgumentCaptor<SubmitWorkflowCommand> captor = ArgumentCaptor.forClass(SubmitWorkflowCommand.class);
		verify(service).submit(captor.capture());
		assertEquals("01964c38-1c45-7000-8000-000000000000", captor.getValue().idempotencyKey());
		assertEquals(
			"run_submit1234 submitted (state: Inbox) [generated-idempotency-key: 01964c38-1c45-7000-8000-000000000000]",
			output);
	}

	@Test
	void autoGeneratedKeyIsSurfacedEvenWithoutVerbose() {
		WorkflowCommandService service = mock(WorkflowCommandService.class);
		when(service.submit(any())).thenReturn(new SubmitWorkflowResult(
			"run_submit1234",
			WorkflowState.INBOX,
			"corr-submit-1"));
		WorkflowCommands commands = new WorkflowCommands(
			service,
			() -> true,
			() -> "01964c38-1c45-7000-8000-000000000000");

		String output = commands.submit(
			"LIN-123",
			"alex",
			ActorType.HUMAN,
			null,
			"corr-submit-1",
			false);

		assertEquals(
			"run_submit1234 submitted (state: Inbox) [generated-idempotency-key: 01964c38-1c45-7000-8000-000000000000]",
			output);
	}

	@Test
	void nonInteractiveSubmitRequiresAnExplicitKey() {
		WorkflowCommandService service = mock(WorkflowCommandService.class);
		WorkflowCommands commands = new WorkflowCommands(
			service,
			() -> false,
			() -> "01964c38-1c45-7000-8000-000000000000");

		DomainException error = assertThrows(
			DomainException.class,
			() -> commands.submit(
				"LIN-123",
				"alex",
				ActorType.HUMAN,
				null,
				"corr-submit-1",
				false));

		assertEquals(DomainErrorCode.MISSING_IDEMPOTENCY_KEY, error.errorCode());
		verifyNoInteractions(service);
	}
}
